### ISSUE TITLE
Code Review of Tweet Generator Submission 2

### ISSUE THREAD

**Issue by SWHarrison** [HexSeal/Tweet-Generator#2]
- Length takes O(n) time. If you keep track of the length of the linked list as you add or remove nodes, you can make it a constant time operation.
- All tests pass with no errors, great job!
- I am not seeing any stretch challenges currently. I recommend trying out the length and utterable challenges, both will be very useful later!

**Comment by MaxIsWell42** [comment]
Thank you, I will try to complete those stretch challenges after I fix the length comment!
